version: "3.9"
services:
  geth:
    image: ethereum/client-go:stable
    container_name: geth
    command: >
      --mainnet
      --syncmode snap
      --http --http.addr 0.0.0.0 --http.port 8545
      --http.api eth,net,web3,txpool
      --http.corsdomain "*"
      --http.vhosts "*"
      --ws --ws.addr 0.0.0.0 --ws.port 8546
      --ws.api eth,net,web3,txpool
      --authrpc.addr 0.0.0.0
      --authrpc.port 8551
      --authrpc.jwtsecret /jwt/jwt.hex
      --maxpeers 50
    ports:
      - "8545:8545"
      - "8546:8546"
      - "8551:8551"
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - ./geth-data:/root/.ethereum
      - ./jwt:/jwt
    restart: unless-stopped

  lighthouse:
    image: sigp/lighthouse:latest
    container_name: lighthouse
    depends_on:
      - geth
    command: >
      lighthouse bn
      --network mainnet
      --execution-endpoint http://geth:8551
      --execution-jwt /jwt/jwt.hex
      --checkpoint-sync-url https://mainnet.checkpoint.sigp.io
      --http --http-address 0.0.0.0 --http-port 5052
    ports:
      - "127.0.0.1:5052:5052"
    volumes:
      - ./lighthouse-data:/root/.lighthouse
      - ./jwt:/jwt
    restart: unless-stopped

  goapi:
    build: ./go-api
    container_name: eth-edu-goapi
    env_file: .env
    environment:
      - RPC_HTTP_URL=${RPC_HTTP_URL-http://geth:8545}
      - BEACON_API_URL=${BEACON_API_URL-http://lighthouse:5052}
      - RELAY_URLS=${RELAY_URLS-https://boost-relay.flashbots.net}
    depends_on:
      - geth
    ports:
      - "127.0.0.1:8080:8080"
    restart: unless-stopped

  web:
    build: ./web
    container_name: eth-edu-web
    env_file: .env
    environment:
      - GOAPI_ORIGIN=http://goapi:8080
    ports:
      - "3000:3000"
    depends_on:
      - goapi
    restart: unless-stopped
